### ISSUE TITLE
CUDA out of memory on preprocess.py

### ISSUE THREAD

**Issue by InterStella0** [lordmartian/deep_avsr#45]
## Issue
I keep getting CUDA out of memory error from preprocessing my data. I ran the `video_only/preprocess.py` to preprocess LRS-3 dataset. I always ran into this issue on the same file.  

**Traceback**
```python

Number of data samples to be processed = 21864


Starting preprocessing ....

Preprocess:  36%|██████▊            | 7830/21864 [37:01<3:02:49,  1.28it/s]
Ignoring error for /content/Dataset/Part 6/kSZEsPnhIXg/00005: CUDA out of memory. Tried to allocate 47.83 GiB (GPU 0; 39.59 GiB total capacity; 13.32 GiB already allocated; 24.53 GiB free; 13.34 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/content/drive/MyDrive/FYP/deep_avsr/video_only/preprocess.py", line 53, in main
    preprocess_sample(file, params)
  File "/content/drive/MyDrive/FYP/deep_avsr/video_only/utils/preprocessing.py", line 58, in preprocess_sample
    outputBatch = vf(inputBatch)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/FYP/deep_avsr/video_only/models/visual_frontend.py", line 107, in forward
    batch = self.frontend3D(inputBatch)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 607, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 603, in _conv_forward
    input, weight, bias, self.stride, self.padding, self.dilation, self.groups
RuntimeError: CUDA out of memory. Tried to allocate 47.83 GiB (GPU 0; 39.59 GiB total capacity; 13.32 GiB already allocated; 24.53 GiB free; 13.34 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

## Workaround
I have tried setting `max_split_size_mb` on `PYTORCH_CUDA_ALLOC_CONF` environment variable and it would still have this issue.
I set the value to 1, 10, 1024, and 2048. None have worked.

I'm forced to work around it by catching the error and deleting the file that causes the out of memory because it's always the same file that is causing it. 
My workaround in `video_only/preprocess.py`
```python
    def silent_rem(file):
        with contextlib.suppress(OSError):
            os.remove(file)
            
    for file in tqdm(filesList, leave=True, desc="Preprocess", ncols=75):
        try:
            preprocess_sample(file, params)
        except RuntimeError as e:
            print(f"\nIgnoring error for {file}:", e, file=sys.stderr)
            traceback.print_exc()
            silent_rem(file + ".txt")
            silent_rem(file + ".mp4")
            silent_rem(file + ".npy")
            silent_rem(file + ".png")
        finally:
            torch.cuda.empty_cache()
```
I don't really like this but it's the only way I can solve this and move forward. It would be really helpful if there is a way to fix it.

## System Information
I've run it on 2 separate machines with the same issue occurring on different files.
- Google Colab Pro+ on GPU Runtime 40GB Memory with 52 GB RAM, Ubuntu 18
  - Python 3.7.14
  - torch==1.12.1+cu113
  - torchaudio==0.12.1+cu113
  - torchvision==0.13.1+cu113
- RTX 3060 (Laptop) 8GB Memory with 16 GB RAM, Windows 11
  - Python 3.6.7
  - torch==1.10.2+cu113
  - torchaudio==0.10.2+cu113
  - torchvision==0.11.3+cu113

**Comment by lordmartian** [comment]
Please check #3.
