### ISSUE TITLE
Error happening when evaluating

### ISSUE THREAD

**Issue by wcycqjy** [lordmartian/deep_avsr#51]
Hi. Thank you for sharing your codes. When I run the train.py, an error happens. When the code goes to 
validationLoss, validationCER, validationWER = evaluate(model, valLoader, loss_function, device, valParams), the traceback occurs
Traceback (most recent call last):
  File "D:\avsr\deep_avsr\audio_visual\train.py", line 160, in <module>
    main()
  File "D:\avsr\deep_avsr\audio_visual\train.py", line 114, in main
    validationLoss, validationCER, validationWER = evaluate(model, valLoader, loss_function, device, valParams)
  File "D:\avsr\deep_avsr\audio_visual\utils\general.py", line 84, in evaluate
    for batch, (inputBatch, targetBatch, inputLenBatch, targetLenBatch) in enumerate(tqdm(evalLoader, leave=False, desc="Eval",
  File "D:\Anaconda3\envs\autoavsr\lib\site-packages\tqdm\std.py", line 1182, in __iter_
    for obj in iterable:
  File "D:\Anaconda3\envs\autoavsr\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "D:\Anaconda3\envs\autoavsr\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "D:\Anaconda3\envs\autoavsr\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "D:\Anaconda3\envs\autoavsr\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 5.
Original Traceback (most recent call last):
  File "D:\Anaconda3\envs\autoavsr\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda3\envs\autoavsr\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\autoavsr\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\avsr\deep_avsr\audio_visual\data\lrs2_dataset.py", line 112, in __getitem__
    inp, trgt, inpLen, trgtLen = prepare_main_input(audioFile, visualFeaturesFile, targetFile, noise, self.reqInpLen, self.charToIx,
  File "D:\avsr\deep_avsr\audio_visual\data\utils.py", line 27, in prepare_main_input
    with open(targetFile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/lrs2_v1/main/.txt'

So it appears to be something cannot be found. This is weired since the training process works but the error happens to the evaluating though I think the dataloaders' structure for these two process are similar. Can you help me fix this problem?

**Comment by wcycqjy** [comment]
I found it's because the space exisiting at the end of val.txt. It's fixed after deleting the space.
